### ISSUE TITLE
Cities of JK's North - eFPS [Patch Request]: 

### ISSUE THREAD

**Issue by exnersen** [mosharky/Ongoing-Patches#4]
### Describe your patch request

There is a patch already present in eFPS Official Patch Hub, but since v5 was released, the patch broke.
Especially in Winterhold, the Occlusion Planes cause disappearing and reappearing of objects with and without the patch for the old version.

Was wondering if you were using eFPS and since nobody has updated the patch yet, I'm requesting it here.
Good Work btw! Ty

### Checklist

- [X] Does not already exist
- [X] Would only contain ESPs or mesh fixes
- [X] Was not already requested
- [X] Is not a symptom of a load order issue (if unsure, its okay to leave unticked)
- [X] May not be considered

**Comment by mosharky** [comment]
Have you requested them to update it? If not I'll look into it sometime

**Comment by exnersen** [comment]
Several other people have pointed out that the patch is outdated on the efps official patch hub nexus and on jk's north patch nexus where Gardden, the man, the myth, the legend, himself said "I'll see if I can update it myself :)". Problem is that the comment I quote was made in late november and the official patch hub hasn't been updated since march.
Idk if there's a way to ask Gardden directly if he's made any progress, so I figured I'd post it here. 
Big Thank You regardless of whether you look into it or not!

**Comment by mosharky** [comment]
I'll see if he has any progress on that sometime. if not, I sorta have to justify making this patch to myself since I don't use his patch at the moment and I'd rather spent time making patches for stuff I do actually use. If I have an abundance of time later down the line I'll check it out but chances are that it's gonna be a real chore to work on and I'd just rather patch something else.

**Comment by mosharky** [comment]
Garrden has made his own patch!
