### ISSUE TITLE
[Patch Request]: The Great Cities of JK's North - Northern Roads

### ISSUE THREAD

**Issue by SiIvervale** [mosharky/Ongoing-Patches#5]
### The Great Cities of JK's North - Northern Roads

Would it be possible to get a northern roads patch for all of these? I know it would be a huge undertaking but it would be absolutely amazing!

### Checklist

- [X] Does not already exist
- [X] Would only contain ESPs or mesh fixes
- [X] Was not already requested
- [ ] Is not a symptom of a load order issue (if unsure, its okay to leave unticked)
- [X] May not be considered

**Comment by mosharky** [comment]
If I were to do this, I'd probably do this for the individual TGC mods, instead of the all-in-one TGC that The Great Cities of JK's North uses. It seems like the modding community is moving towards patching and using the individual mods instead, so it would only make sense in terms of future proofing my work.

That being said, if its not already done, then maybe. Landscape patching is very different and takes a lot of time to learn it seems like. I'll wait for ra2phoenix to make a guide or something lol
